import './globals.css'
import '../../public/fonts/fontstyle.css';
import '../styles/tailwind.module.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
